# Generated by Django 5.0.6 on 2024-05-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=255)),
                ('reg_email', models.EmailField(max_length=255)),
                ('reg_phone', models.CharField(max_length=255)),
                ('reg_user', models.CharField(max_length=255)),
                ('reg_pswd', models.CharField(max_length=255)),
            ],
        ),
    ]
