# Generated by Django 5.0.6 on 2024-05-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_user', models.CharField(max_length=255)),
                ('log_pswd', models.CharField(max_length=255)),
            ],
        ),
    ]
