# Generated by Django 5.0.6 on 2024-07-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
