# Generated by Django 5.0.6 on 2024-07-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_category_category_id_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='cat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_des',
            field=models.TextField(null=True),
        ),
    ]
