# Generated by Django 5.0.6 on 2024-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_id',
            field=models.IntegerField(null=True),
        ),
    ]
