# Generated by Django 5.0.6 on 2024-08-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_product_pro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_image',
            field=models.FileField(null=True, upload_to='wishlist'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_des',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_price',
            field=models.FloatField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_productId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
