# Generated by Django 5.0.6 on 2024-08-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_wishlist_product_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_price',
            field=models.FloatField(default=0.0, max_length=250),
        ),
    ]
