# Generated by Django 5.0.6 on 2024-08-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_wishlist_wishlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_price',
            field=models.FloatField(max_length=250, null=True),
        ),
    ]
