# Generated by Django 5.0.6 on 2024-08-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_wishlist_wishlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_price',
            field=models.IntegerField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_productId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
