# Generated by Django 5.0.6 on 2024-08-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_wishlist_wishlist_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
