# Generated by Django 5.0.6 on 2024-08-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
