# Generated by Django 5.0.6 on 2024-08-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_price',
            field=models.FloatField(null=True),
        ),
    ]
