# Generated by Django 5.0.6 on 2024-08-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_wishlist_wishlist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_price',
        ),
    ]
