# Generated by Django 5.0.6 on 2024-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_user', models.CharField(default='', max_length=255)),
                ('wishlist_productId', models.CharField(max_length=255, null=True)),
                ('product_image', models.FileField(null=True, upload_to='wishlist')),
                ('wishlist_name', models.CharField(default='', max_length=250)),
                ('wishlist_des', models.TextField(null=True)),
            ],
        ),
    ]
