# Generated by Django 5.0.6 on 2024-08-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Wishlist1',
        ),
    ]
