# Generated by Django 5.0.6 on 2024-08-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_rename_wishlist_wishlist1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist1',
            new_name='Wishlist',
        ),
    ]
