# Generated by Django 5.0.6 on 2024-08-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_rename_wishlist1_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_user',
            field=models.CharField(max_length=255),
        ),
    ]
