# Generated by Django 5.0.6 on 2024-08-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_wishlist_wishlist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_image',
            new_name='pro_image',
        ),
    ]
