# Generated by Django 5.0.6 on 2024-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_rename_product_image_wishlist_pro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_price',
            field=models.FloatField(max_length=250, null=True),
        ),
    ]
