# Generated by Django 5.0.6 on 2024-08-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_wishlist_wishlist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='pro_image',
            new_name='wishlist_image',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_des',
        ),
    ]
