# Generated by Django 5.0.6 on 2024-08-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_rename_pro_image_wishlist_wishlist_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcate_user', models.CharField(max_length=255)),
                ('subcate_id', models.CharField(max_length=255, null=True)),
                ('subcate_name', models.CharField(max_length=250)),
            ],
        ),
    ]
